### ISSUE TITLE
Lazy Load Images?

### ISSUE THREAD

**Issue by shaunrobinson** [oli-laban/alpine-tailwind-lightbox#2]
Is there any way to only load the images once someone actually clicks a thumbnail?

Currently every image is loaded as soon as the page loads, which can make it quite a heavy page if you want to have an optional gallery only appear when someone clicks.

Thanks!

**Comment by shaunrobinson** [comment]
I see you added this feature but kept the issue open, does it work? Thanks!

**Comment by oli-laban** [comment]
@shaunrobinson Yes, just have some other changes to release alongside it. Will hopefully get chance to publish the new version tomorrow

**Comment by oli-laban** [comment]
@shaunrobinson This is now released in 1.1.0. Take a look at the updated readme

**Comment by shaunrobinson** [comment]
Thanks, works great!
