### ISSUE TITLE
Lazy Load when using $lightbox?

### ISSUE THREAD

**Issue by shaunrobinson** [oli-laban/alpine-tailwind-lightbox#5]
Just checking I haven't missed something obvious - is it possible to lazy load the images when using $lightbox?

If so, how would you change your demo code to do this?

**Comment by oli-laban** [comment]
@shaunrobinson Yeah this is possible if you pass the images as objects and set `lazy: true`.

**Comment by shaunrobinson** [comment]
Can you give me some example code to do this? Thanks!

**Comment by oli-laban** [comment]
@shaunrobinson Sure, something like:

```html
<div
    x-data="{
        images: [
            { url: 'image-1.jpg', lazy: true },
            { url: 'image-2.jpg', lazy: true },
            { url: 'image-3.jpg', lazy: true },
        ],
    }"
    x-init="$lightbox(images)"
>
    ...
</div>
```

**Comment by shaunrobinson** [comment]
Perfect, thanks!
